-- UNIDAD
ALTER TABLE receta.unidad
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- INGREDIENTE
ALTER TABLE receta.ingrediente
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- MARCA
ALTER TABLE receta.marca
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- TAGS
ALTER TABLE receta.tags
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- TIPO
ALTER TABLE receta.tipo
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- RECETA_PASOS
ALTER TABLE receta.receta_pasos
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- DETALLE_ENTRADA
ALTER TABLE receta.detalle_entrada
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- DETALLE_SALIDA
ALTER TABLE receta.detalle_salida
  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;